const N='odoo-mcp-pro',V='1.0.1-cloudflare',P='2025-03-26';let C=null,U=null;
const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','cache-control':'no-store',...h}});
async function L(e){let r=await fetch(e.ODOO_URL+'/web/session/authenticate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'call',id:1,params:{db:e.ODOO_DB,login:e.ODOO_USERNAME,password:e.ODOO_PASSWORD}}),redirect:'manual'}),d=await r.json().catch(()=>null);if(!r.ok||d?.error||!d?.result?.uid)throw Error(d?.error?.data?.message||d?.error?.message||`Odoo login failed (${r.status})`);let m=(r.headers.get('set-cookie')||'').match(/session_id=([^;]+)/);if(!m)throw Error('Missing Odoo session cookie');C='session_id='+m[1];return U=d.result.uid}
async function Q1(e,m,k,a=[],w={}){if(!C)await L(e);let r=await fetch(`${e.ODOO_URL}/web/dataset/call_kw/${encodeURIComponent(m)}/${encodeURIComponent(k)}`,{method:'POST',headers:{'content-type':'application/json',cookie:C},body:JSON.stringify({jsonrpc:'2.0',method:'call',id:Date.now(),params:{model:m,method:k,args:a,kwargs:w}}),redirect:'manual'}),d=await r.json().catch(()=>null);return[r,d]}
async function Q(e,m,k,a=[],w={}){let[r,d]=await Q1(e,m,k,a,w),z=JSON.stringify(d?.error||{}).toLowerCase();if(r.status==401||r.status==403||z.includes('sessionexpired')||z.includes('session expired')){C=U=null;await L(e);[r,d]=await Q1(e,m,k,a,w)}if(!r.ok)throw Error('Odoo HTTP '+r.status);if(!d)throw Error('Odoo returned non-JSON');if(d.error)throw Error(d.error?.data?.message||d.error?.message||'Odoo RPC error');return d.result}
const S={type:'object',additionalProperties:true};
const T=[['server_info','Connection status'],['list_models','List models'],['model_fields','Model fields'],['search_records','Search records'],['get_record','Get record'],['create_record','Create record'],['update_record','Update record'],['delete_record','Delete record'],['create_records','Create records'],['update_records','Update records'],['delete_records','Delete records'],['import_records','Import records'],['execute_method','Call public Odoo method']].map(([name,description])=>({name,description,inputSchema:S}));
async function R(e,n,i={}){switch(n){case'server_info':try{let u=U||await L(e),r=await fetch(e.ODOO_URL+'/web/version',{redirect:'manual'}),v=await r.json().catch(()=>({}));return{version:V,transport:'streamable-http',connected:true,uid:u,odoo_url:e.ODOO_URL,odoo_version:v.version||v.server_version||null}}catch(x){return{version:V,connected:false,error:String(x.message||x)}}case'list_models':return Q(e,'ir.model','search_read',[[]],{fields:['model','name'],limit:Math.min(i.limit||1000,5000),order:'model asc'});case'model_fields':return Q(e,i.model,'fields_get',[],i.attributes?{attributes:i.attributes}:{});case'search_records':{let w={limit:i.limit||100,offset:i.offset||0};if(i.fields)w.fields=i.fields;if(i.order)w.order=i.order;return Q(e,i.model,'search_read',[i.domain||[]],w)}case'get_record':{let a=await Q(e,i.model,'read',[[i.record_id]],i.fields?{fields:i.fields}:{});if(!a?.length)throw Error('Record not found');return a[0]}case'create_record':{let a=await Q(e,i.model,'create',[[i.values]],{}),id=Array.isArray(a)?a[0]:a;return{id,created:true}}case'update_record':return{id:i.record_id,updated:!!await Q(e,i.model,'write',[[i.record_id],i.values],{})};case'delete_record':return{id:i.record_id,deleted:!!await Q(e,i.model,'unlink',[[i.record_id]],{})};case'create_records':{let a=await Q(e,i.model,'create',[i.vals_list],{}),ids=Array.isArray(a)?a:[a];return{ids,count:ids.length}}case'update_records':return{ids:i.record_ids,count:i.record_ids.length,updated:!!await Q(e,i.model,'write',[i.record_ids,i.values],{})};case'delete_records':return{ids:i.record_ids,count:i.record_ids.length,deleted:!!await Q(e,i.model,'unlink',[i.record_ids],{})};case'import_records':return Q(e,i.model,'load',[i.fields,i.data],i.context?{context:i.context}:{});case'execute_method':if(!i.method||i.method.startsWith('_'))throw Error('Private Odoo methods are not allowed');{let a=[];if(Array.isArray(i.ids))a.push(i.ids);if(Array.isArray(i.args))a.push(...i.args);return Q(e,i.model,i.method,a,i.kwargs||{})}default:throw Error('Unknown tool')}}
const OK=(id,result)=>({jsonrpc:'2.0',id,result}),ER=(id,code,message)=>({jsonrpc:'2.0',id:id??null,error:{code,message}});
async function H(e,m){if(!m||m.jsonrpc!='2.0'||typeof m.method!='string')return ER(m?.id,-32600,'Invalid Request');let id=m.id;if(m.method=='initialize')return OK(id,{protocolVersion:m.params?.protocolVersion||P,capabilities:{tools:{listChanged:false}},serverInfo:{name:N,version:V}});if(m.method=='ping')return OK(id,{});if(m.method=='notifications/initialized'||m.method=='notifications/cancelled')return null;if(m.method=='tools/list')return OK(id,{tools:T});if(m.method=='tools/call'){let n=m.params?.name,i=m.params?.arguments||{};if(!T.some(t=>t.name==n))return ER(id,-32602,'Unknown tool');try{let x=await R(e,n,i);return OK(id,{content:[{type:'text',text:JSON.stringify(x,null,2)}],structuredContent:x})}catch(x){return OK(id,{content:[{type:'text',text:'Error: '+String(x.message||x)}],isError:true})}}return ER(id,-32601,'Method not found')}
async function A(r,x){let u=new URL(r.url),a=r.headers.get('authorization')||'',g=a.replace(/^Bearer\s+/i,'')||u.searchParams.get('token')||'';if(!g||!x)return false;let E=new TextEncoder(),[p,q]=await Promise.all([crypto.subtle.digest('SHA-256',E.encode(g)),crypto.subtle.digest('SHA-256',E.encode(x))]),aa=new Uint8Array(p),bb=new Uint8Array(q),d=aa.length^bb.length;for(let i=0;i<Math.min(aa.length,bb.length);i++)d|=aa[i]^bb[i];return d===0}
export default{async fetch(r,e){let u=new URL(r.url);if(r.method=='GET'&&u.pathname=='/health')try{return J({status:'ok',name:N,version:V,odoo_connected:true,uid:U||await L(e)})}catch(x){return J({status:'degraded',name:N,version:V,odoo_connected:false,error:String(x.message||x)},503)}if(u.pathname!='/mcp')return J({error:'Not found'},404);if(!await A(r,e.MCP_AUTH_TOKEN))return J({error:'Unauthorized'},401,{'www-authenticate':'Bearer'});if(r.method=='DELETE')return new Response(null,{status:204});if(r.method!='POST')return J({error:'Method not allowed'},405);let b;try{b=await r.json()}catch{return J(ER(null,-32700,'Parse error'),400)}let z=await H(e,b);return z===null?new Response(null,{status:202}):J(z,200,{'mcp-protocol-version':P})}};
